FROM node:20-alpine AS builder

WORKDIR /app

RUN apk add --no-cache python3 make g++ cairo-dev jpeg-dev pango-dev giflib-dev pixman-dev eudev-dev libusb-dev openssl

COPY package*.json ./

RUN npm ci

COPY . .

RUN npx prisma generate

RUN npm run build

FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl python3 make g++ cairo-dev jpeg-dev pango-dev giflib-dev pixman-dev eudev-dev libusb-dev

COPY package*.json ./

RUN npm ci --only=production

COPY --from=builder /app/dist dist

COPY --from=builder /app/node_modules/.prisma node_modules/.prisma

EXPOSE 3000
EXPOSE 3001

CMD ["node", "dist/main.js"]
